In [2]:
import pandas as pd
import numpy as np

np.random.seed(0)

n = 1500

# Creation of the DataFrame
df = pd.DataFrame({
    "age_group" : np.random.choice(
        ["18-34", "35-49", "50-64", "65+"],
        size = n,
        p=[0.3, 0.25, 0.25, 0.2]
    ),
    "sex": np.random.choice(["Female", "Male"], size=n),
    "insurance": np.random.choice(
        ["Private", "Public", "Uninsured"], 
        size=n, 
        p=[0.5, 0.35, 0.15]
    ),
    "preventive_visit": np.random.choice(
        ["Yes", "No"], 
        size=n, 
        p=[0.55, 0.45]
    )
})

# First 5 rows
df.head()

  age_group     sex  insurance preventive_visit
0     35-49    Male  Uninsured               No
1     50-64    Male     Public              Yes
2     50-64    Male     Public               No
3     35-49  Female    Private               No
4     35-49  Female    Private              Yes

In [3]:
# The size of the DataFrame
df.shape

(1500, 4)

In [4]:
# Quick Check on the DataFrame
df.describe()

       age_group   sex insurance preventive_visit
count       1500  1500      1500             1500
unique         4     2         3                2
top        18-34  Male   Private              Yes
freq         458   768       767              871

In [5]:
# Base probability a individual in our system is using or not
df["preventive_visit"].value_counts(normalize=True)

preventive_visit
Yes    0.580667
No     0.419333
Name: proportion, dtype: float64

In [6]:
pd.crosstab(
    df["insurance"],
    df["preventive_visit"],
    normalize="index"
)

preventive_visit        No       Yes
insurance
Private           0.405476  0.594524
Public            0.428850  0.571150
Uninsured         0.445455  0.554545

In [8]:
pd.crosstab(
    df["age_group"],
    df["preventive_visit"],
    normalize="index"
)

preventive_visit        No       Yes
age_group
18-34             0.412664  0.587336
35-49             0.461333  0.538667
50-64             0.383523  0.616477
65+               0.419048  0.580952